services:
  frontend:
    container_name: html-frontend
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
  