services:

  frontend:
    container_name: html-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"

  backend:
    container_name: go-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./backend/src:/app

  database:
    container_name: sql-database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrabble-words-db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/words.txt:/docker-entrypoint-initdb.d/words.txt
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
  py-backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - "./backend_py/src:/app"